/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ProductCard: typeof import('./components/ProductCard.vue')['default']
    ProductCardImage: typeof import('./components/ProductCardImage.vue')['default']
    ProductCardImage2: typeof import('./components/ProductCardImage2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
