/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    BCard: typeof import('./components/B/BCard.vue')['default']
    BDashboard: typeof import('./components/B/BDashboard.vue')['default']
    CCard: typeof import('./components/C/CCard.vue')['default']
    CDashboard: typeof import('./components/C/CDashboard.vue')['default']
    LoginForm: typeof import('./components/auth/LoginForm.vue')['default']
    RegisterForm: typeof import('./components/auth/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
