/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    BCard: typeof import('./components/B/BCard.vue')['default']
    BDashboard: typeof import('./components/B/BDashboard.vue')['default']
    CCard: typeof import('./components/C/CCard.vue')['default']
    CDashboard: typeof import('./components/C/CDashboard.vue')['default']
    ProductCard: typeof import('./components/ProductCard.vue')['default']
    ProductCardImage: typeof import('./components/ProductCardImage.vue')['default']
    ProductCardImage2: typeof import('./components/ProductCardImage2.vue')['default']
    ProfileCard: typeof import('../../profile/src/components/ProfileCard.vue')['default']
    ProfileImage: typeof import('../../profile/src/components/ProfileImage.vue')['default']
    ProfileImage2: typeof import('../../profile/src/components/ProfileImage2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
