name: Frontend CI/CD

on:
  push:
    branches:
      - main
      - mf
  pull_request:
    branches:
      - main
      - mf

jobs:
  build-root:
    name: Root - Install, Lint, Test, and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: apps/root

      - name: Run Linter
        run: npm run lint
        working-directory: apps/root

      - name: Run Tests
        run: npm run test
        working-directory: apps/root

      - name: Build project
        run: npm run build
        working-directory: apps/root

  deploy-root:
    name: Root - Deploy to GitHub Pages
    needs: build-root
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: apps/root/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: apps/root

      - name: Build project
        run: npm run build
        working-directory: apps/root

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: apps/root/dist

  build-b:
    name: B - Install, Lint, Test, and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: apps/b

      - name: Run Linter
        run: npm run lint
        working-directory: apps/b

      - name: Run Tests
        run: npm run test
        working-directory: apps/b

      - name: Build project
        run: npm run build
        working-directory: apps/b

  deploy-b:
    name: B - Deploy to GitHub Pages
    needs: build-b
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: apps/b/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: apps/b

      - name: Build project
        run: npm run build
        working-directory: apps/b

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: apps/b/dist

  build-c:
    name: C - Install, Lint, Test, and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: apps/c

      - name: Run Linter
        run: npm run lint
        working-directory: apps/c

      - name: Run Tests
        run: npm run test
        working-directory: apps/c

      - name: Build project
        run: npm run build
        working-directory: apps/c

  deploy-c:
    name: C - Deploy to GitHub Pages
    needs: build-c
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: apps/c/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: apps/c

      - name: Build project
        run: npm run build
        working-directory: apps/c

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: apps/c/dist